language: node_js
sudo: false
git:
  depth: 10

jobs:
  include:
    - os: linux
      node_js: '8'
    - os: linux
      node_js: '10'
    - os: linux
      node_js: '12'
    - os: windows
      node_js: 'node/8'
    - os: windows
      node_js: 'node/10'
    - os: windows
      node_js: 'node/12'

install:
  - npm version
  - npm install -g codecov
  - npm install

script:
  - npm test

after_success:
  - codecov

# safelist (prevent double builds in PRs)
branches:
  only:
    - master
    - /^greenkeeper/.*$/
